# Generated by Django 4.0.6 on 2022-07-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_rename_recipeingredient_amountingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amountingredient',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
    ]
